services:
  flask-api:
    container_name: focus-container
    image: focus-track-dimage:dev
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance/selections.db:/app/selections.db
    environment:
      - FLASK_ENV=development
      

  # Later: nicegui, streamlit